import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Clock3, MoveRight } from "lucide-react";
import { Footer, ProgramCard, Reveal, SiteNav, WhatsAppFab, programs, useReveals } from "@/components/prakrithi-site";

export const Route = createFileRoute("/programs")({
  head: () => ({ meta: [{ title: "Programs — Prakrithi Yoga Studio" }, { name: "description", content: "Explore breath-led yoga, flow, meditation, and breathwork classes in a warm, welcoming studio." }, { property: "og:title", content: "Programs — Prakrithi Yoga Studio" }, { property: "og:description", content: "Explore breath-led yoga, flow, meditation, and breathwork classes in a warm, welcoming studio." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: ProgramsPage,
});

function ProgramsPage() { useReveals(); return <div><SiteNav /><WhatsAppFab /><main><section className="relative overflow-hidden bg-charcoal pb-20 pt-40 text-background md:pb-28 md:pt-48"><div className="page-container grid items-end gap-10 md:grid-cols-[1.1fr_0.9fr]"><Reveal><p className="eyebrow text-primary">Prakrithi / Programs</p><h1 className="mt-6 max-w-4xl display-serif text-7xl leading-[0.8] sm:text-8xl md:text-[9rem]">Find your <em className="text-primary">practice.</em></h1></Reveal><Reveal><p className="max-w-sm text-sm leading-7 text-background/60">A considered collection of classes for wherever you are in your practice — from your very first breath to your deepest flow.</p></Reveal></div></section><section className="bg-cream py-24 md:py-36"><div className="page-container"><Reveal><p className="eyebrow text-primary">The studio schedule</p><h2 className="mt-4 display-serif text-5xl text-foreground md:text-7xl">Move at your own <em className="text-primary">pace.</em></h2></Reveal><div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{programs.map((program) => <Reveal key={program.id} image><Link to="/contact" className="group block overflow-hidden border border-border bg-linen"><div className="relative aspect-[1.2] overflow-hidden"><img src={program.id === "studio-tour" ? undefined : undefined} alt="" className="hidden" /><ProgramCard program={program} /></div><div className="p-6"><p className="eyebrow text-primary">{program.category}</p><h3 className="mt-3 display-serif text-3xl text-foreground">{program.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{program.longDescription}</p><div className="mt-6 flex items-center justify-between border-t border-border pt-4 text-xs text-muted-foreground"><span className="inline-flex items-center gap-2"><Clock3 className="size-3.5 text-primary" />{program.duration}</span><span>{program.level}</span></div><span className="mt-5 inline-flex items-center gap-2 text-xs font-medium uppercase tracking-[0.12em] text-foreground group-hover:text-primary">Enquire about this class <ArrowRight className="size-3.5" /></span></div></Link></Reveal>)}</div></div></section><section className="bg-linen py-24 md:py-32"><div className="page-container flex flex-col items-start justify-between gap-8 md:flex-row md:items-center"><div><p className="eyebrow text-primary">Not sure where to begin?</p><h2 className="mt-4 display-serif text-5xl leading-[0.9] text-foreground md:text-7xl">Start with a <em className="text-primary">conversation.</em></h2></div><Link to="/contact" className="inline-flex items-center gap-3 rounded-full bg-charcoal px-6 py-3 text-xs font-medium uppercase tracking-[0.14em] text-background hover:bg-sage-dark">Talk to us <MoveRight className="size-4" /></Link></div></section></main><Footer /></div>; }